"""The prose FastAPI would otherwise answer with.

An invalid path parameter comes back as ``{"detail": [{"msg": "Input should be
a valid UUID, ..."}]}`` — pydantic's wording, in English, and shaped as a list
rather than a string. The SPA has a branch in ``api/client.ts`` that joins those
``msg`` fields and renders them, so this text has a route to the screen; it is
just not a route the UI takes on its own, which is exactly how one English
sentence survives in a Chinese interface.

The handler replaces the prose and keeps the structure, because the structure is
the diagnostic: ``type`` and ``location`` are what identify the offending field,
and translating them would delete the information rather than soften it.

It replaces the *framework's* prose, though — not everything. A first version
rewrote every message unconditionally, which fixed the English and silently threw
away the Chinese the domain layer had already written: ``severity 取值 'x' 不合法，
必须是 critical、high、low、medium 之一。`` collapsed into ``请求参数不合法：body.severity``.
So the handler keeps the message when pydantic's ``type`` says a validator we
wrote raised it, and substitutes only for the constraint violations pydantic
generated by itself.
"""

from __future__ import annotations

from uuid import UUID

import httpx
import pytest
from fastapi import FastAPI
from fastapi.exceptions import RequestValidationError
from pydantic import BaseModel, field_validator

from opspilot_backend.main import _validation_error_handler


class _Thing(BaseModel):
    # Plain ``str`` with a validator, mirroring ``IncidentCreate.severity``. The
    # shape matters: with ``Literal["low", "high"]`` pydantic rejects the value
    # itself and the validator never runs, so the error type is ``literal_error``
    # and the test would be exercising a path the real schema does not have.
    severity: str

    @field_validator("severity")
    @classmethod
    def _check(cls, v: str) -> str:
        # Shaped like the real validators: a Chinese sentence raised from a
        # ``ValueError``, which pydantic prefixes with "Value error, ".
        if v not in ("low", "high"):
            raise ValueError(f"severity 取值 '{v}' 不合法，必须是 low、high 之一。")
        return v


@pytest.fixture
async def client() -> httpx.AsyncClient:
    """A minimal app carrying the real handler — not the full app.

    The full app's lifespan checks and may rebuild a database on disk, which a
    test of a response shape has no business doing.
    """
    app = FastAPI()
    app.add_exception_handler(RequestValidationError, _validation_error_handler)

    @app.get("/things/{thing_id}")
    async def _get_thing(thing_id: UUID) -> dict[str, str]:  # pragma: no cover
        return {"thing_id": str(thing_id)}

    @app.post("/things")
    async def _post_thing(thing: _Thing) -> dict[str, str]:  # pragma: no cover
        return {"severity": thing.severity}

    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://probe"
    ) as http:
        yield http


async def test_a_malformed_path_parameter_is_answered_in_chinese(
    client: httpx.AsyncClient,
) -> None:
    response = await client.get("/things/not-a-uuid")

    assert response.status_code == 422
    detail = response.json()["detail"]
    assert isinstance(detail, str), "the SPA prefers a string and renders it verbatim"
    assert detail.startswith("请求参数不合法")
    assert "path.thing_id" in detail, "the offending field is what makes it actionable"


async def test_the_diagnostics_survive_in_machine_readable_form(
    client: httpx.AsyncClient,
) -> None:
    payload = (await client.get("/things/not-a-uuid")).json()

    assert payload["errors"], "dropping these would trade a translation for a blind spot"
    assert payload["errors"][0]["type"] == "uuid_parsing"
    assert "thing_id" in payload["errors"][0]["location"]


async def test_a_valid_request_is_untouched(client: httpx.AsyncClient) -> None:
    response = await client.get("/things/3f2504e0-4f89-11d3-9a0c-0305e82c3301")

    assert response.status_code == 200
    assert response.json() == {"thing_id": "3f2504e0-4f89-11d3-9a0c-0305e82c3301"}


async def test_our_own_chinese_message_reaches_the_caller(
    client: httpx.AsyncClient,
) -> None:
    """A message the domain layer wrote must not be replaced by a generic one."""
    response = await client.post("/things", json={"severity": "medium"})

    assert response.status_code == 422
    detail = response.json()["detail"]
    assert "severity 取值 'medium' 不合法" in detail
    assert "low、high" in detail
    assert "Value error" not in detail, "pydantic's prefix is not part of the sentence"


async def test_framework_generated_constraints_are_still_rewritten(
    client: httpx.AsyncClient,
) -> None:
    """The allowlist is by error type, so pydantic's own wording stays hidden.

    ``medium`` fails the ``Literal`` at the type level *and* reaches the
    validator; a value of the wrong Python type only ever fails the framework,
    and that path must still come back Chinese.
    """
    response = await client.post("/things", json={"severity": 3})
    detail = response.json()["detail"]

    assert isinstance(detail, str)
    assert "Input should be" not in detail
    assert "body.severity" in detail or "severity 取值" in detail
