import { useMemo, useState } from 'react'
import { PageHeader, Panel } from '../ui/Panel'
import { Button } from '../ui/Button'
import { Alert, EmptyState, Progress } from '../ui/Feedback'
import { Badge } from '../ui/Badge'
import { Icon } from '../ui/Icon'
import { MetricCard } from '../components/MetricCard'
import { useAgentStats } from '../lib/queries'
import { formatNumber, formatPercent } from '../lib/format'
import { outcomeLabel, outcomeTone } from '../lib/labels'
import { zhCategory } from '../i18n'
import report from '../lib/eval_report.json'

/**
 * The offline benchmark report, as produced by `evals/cli.py`.
 *
 * This file used to be a hand-written 20-case snapshot with a different shape
 * (`avg_steps: 1.0`), which drifted from the suite the moment the suite
 * changed. The CLI now writes this artefact itself — see `_web_report_path`
 * in `evals/cli.py` — so the page is a view of a generated result, not a copy
 * of one. Only the aggregate block is exported; the per-case rows and the run
 * environment stay in `evals/reports/`.
 */
interface EvalReport {
  generated_at: string
  report: {
    total: number
    errors: number
    root_cause_accuracy: number
    evidence_accuracy: { recall: number; utilisation: number; traceability: number }
    tool_selection_accuracy: number
    investigation: {
      avg_steps: number
      avg_distinct_stages: number
      avg_replan_rounds: number
      runs_that_replanned: number
      avg_rejected_hypotheses: number
    }
    recovery: {
      success_rate: number
      environment_fixed_rate: number
      effective_action_rate: number
      rollback_rate: number
    }
    verification: {
      accuracy: number
      scored_runs: number
      reported_success_env_broken: number
    }
    diagnosis_honesty: { false_diagnosis_rate: number; answered: number; abstained: number }
    escalation: { rate: number; reasons: Record<string, number> }
    cost: {
      total_tool_calls: number
      avg_tool_calls: number
      failed_tool_calls: number
      failed_tool_call_rate: number
      total_tokens: number
      avg_tokens: number
      reasoning_modes: Record<string, number>
      budget_exhausted_runs: number
    }
    latency_ms: { avg: number; p50: number; p95: number; max: number; avg_workflow: number }
    trace_integrity: {
      single_root: number
      with_dangling_parents: number
      avg_spans: number
      avg_depth: number
    }
    breakdowns: {
      category: Record<string, number>
      scenario: Record<string, ScenarioScore>
      difficulty: Record<string, number>
      severity: Record<string, number>
    }
    notes: { suite: string; version: string; scoring: Record<string, string> }
  }
}

interface ScenarioScore {
  correct: boolean
  diagnosed: string
  expected: string
  outcome: string
  tools: number
  recall: number
  env_fixed: boolean
  escalated: boolean
  latency_ms: number
}

const REPORT = (report as EvalReport).report
const GENERATED_AT = (report as EvalReport).generated_at

/**
 * EvaluationsPage — the offline quality harness.
 *
 * Two data sources, deliberately kept apart:
 *
 *   * the **offline suite** — ground-truth scenarios scored against the
 *     simulator's answer key, driving the real investigation graph. A fixed
 *     artefact generated by `evals/cli.py`; it answers "is the diagnosis
 *     logic correct?".
 *   * the **live counters** — real agent runs recorded by the backend. This
 *     answers "is the system behaving in production?".
 *
 * Mixing the two would be misleading, so they render in separate tabs with
 * their provenance stated.
 */
export function EvaluationsPage() {
  const statsQ = useAgentStats()
  const [tab, setTab] = useState<'offline' | 'live'>('offline')

  const scenarios = useMemo(
    () => Object.entries(REPORT.breakdowns.scenario).sort(([a], [b]) => a.localeCompare(b)),
    [],
  )
  const categories = useMemo(() => Object.entries(REPORT.breakdowns.category), [])
  const difficulties = useMemo(() => Object.entries(REPORT.breakdowns.difficulty), [])
  const severities = useMemo(() => Object.entries(REPORT.breakdowns.severity), [])
  const scoringDefs = useMemo(() => Object.entries(REPORT.notes.scoring), [])

  const pass = REPORT.root_cause_accuracy >= 0.8

  return (
    <>
      <PageHeader
        title="评估"
        description="离线基准套件与线上运行指标的对照，用来判断诊断逻辑的正确性与系统实际表现。"
        actions={
          <div className="tabs">
            <button
              className={`tab${tab === 'offline' ? ' tab-active' : ''}`}
              onClick={() => setTab('offline')}
            >
              离线基准
            </button>
            <button
              className={`tab${tab === 'live' ? ' tab-active' : ''}`}
              onClick={() => setTab('live')}
            >
              线上指标
            </button>
          </div>
        }
      />

      {tab === 'offline' ? (
        <>
          <Alert tone={pass ? 'success' : 'warning'} title={`基准套件 · ${REPORT.total} 条 ground-truth 场景`}>
            <span className="mono">
              确定性运行，不调用 LLM、不访问网络。报告生成于 {GENERATED_AT}，由{' '}
              <code>python evals/cli.py</code> 产出。
              {REPORT.errors > 0 && ` 本次有 ${REPORT.errors} 个场景执行报错。`}
            </span>
          </Alert>

          <div className="metric-grid">
            <MetricCard
              label="根因准确率"
              value={formatPercent(REPORT.root_cause_accuracy, 0)}
              tone={pass ? 'success' : 'warning'}
              sub={`${REPORT.total} 条场景`}
            />
            <MetricCard
              label="工具覆盖"
              value={formatPercent(REPORT.tool_selection_accuracy, 0)}
              tone="agent"
              sub="所需工具族全部被调用"
            />
            <MetricCard
              label="证据召回"
              value={formatPercent(REPORT.evidence_accuracy.recall, 0)}
              tone="primary"
              sub={`被引用 ${formatPercent(REPORT.evidence_accuracy.utilisation, 0)}`}
            />
            <MetricCard
              label="平均耗时"
              value={formatNumber(REPORT.latency_ms.avg, 0)}
              unit="ms"
              sub={`${REPORT.investigation.avg_steps.toFixed(1)} 步 / 次`}
            />
          </div>

          <div className="eval-grid">
            <Panel title="证据质量" subtitle="取证是否覆盖、是否被用上、是否可追溯">
              <div className="breakdown-list">
                <BreakdownRow label="召回率" score={REPORT.evidence_accuracy.recall} tone="primary" />
                <BreakdownRow
                  label="利用率"
                  score={REPORT.evidence_accuracy.utilisation}
                  tone="agent"
                />
                <BreakdownRow
                  label="可追溯到假设"
                  score={REPORT.evidence_accuracy.traceability}
                  tone="agent"
                />
              </div>
            </Panel>

            <Panel title="调查过程" subtitle="是否真的在探索，而不是一次走完">
              <div className="breakdown-list">
                <StatRow label="平均步数" value={REPORT.investigation.avg_steps.toFixed(1)} />
                <StatRow
                  label="平均经历节点"
                  value={REPORT.investigation.avg_distinct_stages.toFixed(1)}
                />
                <StatRow
                  label="平均重规划轮次"
                  value={REPORT.investigation.avg_replan_rounds.toFixed(1)}
                />
                <StatRow
                  label="发生重规划的运行"
                  value={`${REPORT.investigation.runs_that_replanned} / ${REPORT.total}`}
                />
                <StatRow
                  label="平均被否决假设"
                  value={REPORT.investigation.avg_rejected_hypotheses.toFixed(1)}
                />
              </div>
            </Panel>

            <Panel title="诊断诚实度" subtitle="有没有在证据不足时硬下结论">
              <div className="breakdown-list">
                <BreakdownRow
                  label="误判率"
                  score={1 - REPORT.diagnosis_honesty.false_diagnosis_rate}
                  tone="success"
                />
                <StatRow label="给出了结论" value={String(REPORT.diagnosis_honesty.answered)} />
                <StatRow label="主动弃权" value={String(REPORT.diagnosis_honesty.abstained)} />
                <StatRow
                  label="移交人工"
                  value={`${REPORT.escalation.rate > 0 ? formatPercent(REPORT.escalation.rate, 0) : '未触发'}`}
                />
              </div>
            </Panel>

            <Panel title="恢复与验证" subtitle="方案生成后的闭环质量">
              <div className="breakdown-list">
                <BreakdownRow
                  label="恢复成功率"
                  score={REPORT.recovery.success_rate}
                  tone="success"
                />
                <BreakdownRow
                  label="环境真实修复"
                  score={REPORT.recovery.environment_fixed_rate}
                  tone="success"
                />
                <BreakdownRow
                  label="动作产生实际变化"
                  score={REPORT.recovery.effective_action_rate}
                  tone="primary"
                />
                <BreakdownRow label="回滚率" score={REPORT.recovery.rollback_rate} tone="warning" />
                <StatRow
                  label="验证结论与环境一致"
                  value={`${formatPercent(REPORT.verification.accuracy, 0)} · ${REPORT.verification.scored_runs} 次`}
                />
                <StatRow
                  label="声称修好但环境仍坏"
                  value={
                    REPORT.verification.reported_success_env_broken === 0
                      ? '0 次'
                      : `${REPORT.verification.reported_success_env_broken} 次`
                  }
                />
              </div>
            </Panel>

            <Panel title="成本" subtitle="每次调查调用了多少工具、花了多少 Token">
              <div className="breakdown-list">
                <StatRow
                  label="工具调用总数"
                  value={`${REPORT.cost.total_tool_calls} · 平均 ${REPORT.cost.avg_tool_calls.toFixed(1)}/次`}
                />
                <StatRow
                  label="工具失败率"
                  value={`${formatPercent(REPORT.cost.failed_tool_call_rate, 1)} · ${REPORT.cost.failed_tool_calls} 次`}
                />
                <StatRow
                  label="Token"
                  value={
                    REPORT.cost.total_tokens > 0
                      ? `${REPORT.cost.total_tokens} · 平均 ${REPORT.cost.avg_tokens.toFixed(0)}/次`
                      : '0（确定性推理，不调用模型）'
                  }
                />
                <StatRow
                  label="预算耗尽而中断"
                  value={String(REPORT.cost.budget_exhausted_runs)}
                />
              </div>
            </Panel>

            <Panel title="追踪完整性" subtitle="每次运行是否只有一棵完整的调用树">
              <div className="breakdown-list">
                <StatRow label="单根追踪" value={`${REPORT.trace_integrity.single_root} / ${REPORT.total}`} />
                <StatRow
                  label="存在悬空父跨度"
                  value={
                    REPORT.trace_integrity.with_dangling_parents === 0
                      ? '无'
                      : String(REPORT.trace_integrity.with_dangling_parents)
                  }
                />
                <StatRow
                  label="平均跨度数"
                  value={REPORT.trace_integrity.avg_spans.toFixed(1)}
                />
                <StatRow
                  label="平均深度"
                  value={REPORT.trace_integrity.avg_depth.toFixed(1)}
                />
              </div>
            </Panel>
          </div>

          <div className="eval-grid">
            <Panel title="按分类" subtitle="根因类别命中率">
              <div className="breakdown-list">
                {categories.map(([name, score]) => (
                  <BreakdownRow key={name} label={zhCategory(name)} score={score} />
                ))}
              </div>
            </Panel>

            <Panel title="按难度" subtitle="越难越能验证泛化">
              <div className="breakdown-list">
                {difficulties.length === 0 ? (
                  <EmptyState compact title="无难度标注" />
                ) : (
                  difficulties.map(([name, score]) => (
                    <BreakdownRow
                      key={name}
                      label={difficultyLabel(name)}
                      score={score}
                      tone="agent"
                    />
                  ))
                )}
              </div>
            </Panel>

            <Panel title="按严重度" subtitle="定级是否影响判断质量">
              <div className="breakdown-list">
                {severities.length === 0 ? (
                  <EmptyState compact title="无严重度标注" />
                ) : (
                  severities.map(([name, score]) => (
                    <BreakdownRow key={name} label={name} score={score} tone="primary" />
                  ))
                )}
              </div>
            </Panel>
          </div>

          <Panel
            title="逐场景结果"
            subtitle={`${scenarios.length} 条 · 与模拟器答案键逐条比对`}
            flush
          >
            <div className="table-wrap">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>场景</th>
                    <th style={{ width: 118 }}>期望 / 实际</th>
                    <th style={{ width: 172 }}>结论</th>
                    <th style={{ width: 108 }}>证据召回</th>
                    <th style={{ width: 76 }}>工具</th>
                    <th style={{ width: 76 }}>环境</th>
                    <th style={{ width: 84 }}>耗时</th>
                  </tr>
                </thead>
                <tbody>
                  {scenarios.map(([name, s]) => (
                    <tr key={name}>
                      <td className="col-mono">{name}</td>
                      <td className="col-mono">
                        <span className={s.correct ? '' : 'hl-crit'}>
                          {zhCategory(s.diagnosed)}
                        </span>
                        <span className="muted"> / {zhCategory(s.expected)}</span>
                      </td>
                      <td>
                        <span className={`badge badge-sm badge-${outcomeTone(s.outcome)}`}>
                          {outcomeLabel(s.outcome)}
                        </span>
                        {s.escalated && <span className="badge badge-sm badge-warning">已升级</span>}
                      </td>
                      <td className="col-mono">{formatPercent(s.recall, 0)}</td>
                      <td className="col-mono">{s.tools}</td>
                      <td className={s.env_fixed ? '' : 'hl-crit'}>
                        {s.env_fixed ? '已修复' : '未修复'}
                      </td>
                      <td className="col-mono muted">{formatNumber(s.latency_ms, 0)}ms</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Panel>

          <Panel title="指标定义" subtitle="每一项数字是怎么算出来的">
            <div className="breakdown-list">
              {scoringDefs.map(([key, desc]) => (
                <div className="def-row" key={key}>
                  <span className="def-key mono">{key}</span>
                  <span className="def-desc">{desc}</span>
                </div>
              ))}
            </div>
          </Panel>
        </>
      ) : (
        <>
          <Alert tone="info" title="线上指标 · 来自真实 Agent 运行">
            数据源为后端 <code className="mono">/api/v1/agent/stats</code>，随每次运行实时更新。
          </Alert>

          {statsQ.error ? (
            <Alert tone="critical" title="加载线上统计失败">
              {statsQ.error instanceof Error ? statsQ.error.message : String(statsQ.error)}
            </Alert>
          ) : (
            <div className="metric-grid">
              <MetricCard label="累计运行" value={statsQ.data?.total_runs ?? 0} tone="agent" />
              <MetricCard
                label="已完成"
                value={statsQ.data?.completed ?? 0}
                tone="success"
                sub={`${statsQ.data?.failed ?? 0} 次失败`}
              />
              <MetricCard
                label="成功率"
                value={statsQ.data?.has_data ? formatPercent(statsQ.data.success_rate, 0) : '—'}
              />
              <MetricCard
                label="恢复验证率"
                value={
                  statsQ.data?.recovery_verified
                    ? formatPercent(statsQ.data.recovery_rate, 0)
                    : '—'
                }
                sub={`${statsQ.data?.recovery_attempted ?? 0} 次尝试`}
              />
            </div>
          )}

          <Panel title="运行分布">
            <div className="breakdown-list">
              <BreakdownRow
                label="调查中"
                score={
                  statsQ.data?.total_runs
                    ? (statsQ.data.in_progress ?? 0) / statsQ.data.total_runs
                    : 0
                }
                tone="primary"
              />
              <BreakdownRow
                label="等待审批"
                score={
                  statsQ.data?.total_runs
                    ? (statsQ.data.awaiting_approval ?? 0) / statsQ.data.total_runs
                    : 0
                }
                tone="warning"
              />
              <BreakdownRow
                label="已恢复并验证"
                score={
                  statsQ.data?.total_runs
                    ? (statsQ.data.recovery_verified ?? 0) / statsQ.data.total_runs
                    : 0
                }
                tone="success"
              />
            </div>
          </Panel>

          <div className="row" style={{ marginTop: 'var(--space-4)' }}>
            <Button
              icon={<Icon name="refresh" size={14} />}
              loading={statsQ.isFetching}
              onClick={() => statsQ.refetch()}
            >
              刷新线上指标
            </Button>
          </div>
        </>
      )}
    </>
  )
}

function BreakdownRow({
  label,
  score,
  tone,
}: {
  label: React.ReactNode
  score: number
  tone?: 'success' | 'warning' | 'primary' | 'agent'
}) {
  return (
    <div className="breakdown-row">
      <div className="breakdown-label">{label}</div>
      <div className="breakdown-bar">
        <Progress value={score} tone={tone === 'success' ? 'success' : undefined} />
      </div>
      <div className="breakdown-score mono">{formatPercent(score, 0)}</div>
      {score >= 1 && <Badge tone="success" size="sm">全通过</Badge>}
    </div>
  )
}

/** A plain label/value line — for counts, where a 0-100% bar would be a lie. */
function StatRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="stat-row">
      <span className="stat-label">{label}</span>
      <span className="stat-value mono">{value}</span>
    </div>
  )
}

function difficultyLabel(name: string): string {
  return name === 'easy' ? '简单' : name === 'medium' ? '中等' : name === 'hard' ? '困难' : name
}
